### ISSUE TITLE
Crash when reporting errors from apps published with PublishSingleFile=true

### ISSUE THREAD

**Issue by grahamboree** [backtrace-labs/backtrace-csharp#35]
Relevant callstack:
```
Unhandled exception. System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at Backtrace.Model.JsonData.BacktraceAttributes.SetLibraryAttributes(BacktraceReport report)
   at Backtrace.Model.JsonData.BacktraceAttributes..ctor(BacktraceReport report, Dictionary`2 clientAttributes)
   at Backtrace.Model.BacktraceData.SetAttributes(Dictionary`2 clientAttributes)
   at Backtrace.Model.BacktraceData..ctor(BacktraceReport report, Dictionary`2 clientAttributes)
   at Backtrace.Base.BacktraceBase.Send(BacktraceReport report)
   at Backtrace.BacktraceClient.Send(BacktraceReport backtraceReport)
   at Backtrace.BacktraceClient.Send(Exception exception, Dictionary`2 attributes, List`1 attachmentPaths)
```

The long and short of it is that `BacktraceAttributes.SetLibraryAttributes` is trying to get the calling assembly's location via `Assembly.Location` as a reporting attribute, along with passing it to `FileVersionInfo.GetVersionInfo` to get the version information [here](https://github.com/backtrace-labs/backtrace-csharp/blob/8a84bf76d0132c80084b65773d4003cec6ffa787/Backtrace/Model/JsonData/BacktraceAttributes.cs#L77C41-L77C71).

`Assembly.Location` [always returns the empty string when PublishSingleFile is enabled](https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/warnings/il3000).

To repro the issue:
1.  Add backtrace to an example project and create a BtClient
2.  call `BtClient.Error(new Exception("test"));` in `Main`
3.  `dotnet publish /p:PublishSingleFile=true --self-contained true -r win-x64`
4.  Run the resulting exe

**Comment by konraddysput** [comment]
Hey @grahamboree 

thank you for reporting this issue. The fix should be easy to implement. We will plan to release a new version of the library soon. 

I will notify you about the release once we will be ready to release it.

**Comment by konraddysput** [comment]
hey @grahamboree 

sorry for late reply. The patch that should fix this problem is now available. Please let me know what you think!

**Comment by grahamboree** [comment]
Thanks so much @konraddysput!
